name: FraudDetection

on:
  workflow_dispatch:
    inputs:
      recordId:
        description: 'ID of the transaction'
        required: true
        default: '12345'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Call webhook
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request POST \
          --header 'content-type: application/json' \
          --url '${{ secrets.FRAUDDETECTION_WEBHOOK }}' \
          --data '{ \
          "recordId": '${{ github.event.inputs.recordId }}', \
          "isSuspiciousTransaction": '$(($RANDOM%2 -eq 0))' \
          }'`
          if [ $CODE!="202" ] 
          then
            echo "FAILURE"
          else
            echo "SUCCESS"
          fi
